name: Angular_Build
on:
  push:
    branches:
      - master

jobs:
  angular_build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: npm install and npm run build
        run: |
          cd angular
          npm install
          npm list -g --depth=0
          npm ci
          npm run build:ci 
